### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by greysteil** [swashata/composer-renovate-test#1]
Hey @swashata - I noticed this repo and thought you might want to give [Dependabot](https://dependabot.com) a try on it. Running on my fork I got [these PRs](https://github.com/greysteil/composer-renovate-test). The core logic that generates them is all open source [here](https://github.com/dependabot/dependabot-core).

**Comment by swashata** [comment]
Hi,

I have actually checked but couldn't use it because we have self hosted gitlab for managing our source code, CI/CD etc.

**Comment by greysteil** [comment]
Ah, cool. We'll add support for self-hosted GitLab soon 🙂
